backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $this->layout = 'blank';

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/AjaxController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\web\Controller;
use app\models\MasterCarModel;
use app\models\MasterCarModelGroup;
use app\models\SuperDeals;
use app\models\TransOrder;
use app\models\TransStatisticCount;

/**
 * Ajax controller
 */
class AjaxController extends Controller
{
	public function actionNews() {
		$response_str = Yii::$app->api->wpnews();
		echo $response_str;
	}

	public function actionModel() {
		$response_array = ['result' => 0, 'model' => [], 'message' => 'Unknown error occurred, please try again.'];	

		$from_osc = (isset($_REQUEST['is_osc']) ? (int)$_REQUEST['is_osc'] : 0);

		$master_car_model = new MasterCarModel();
		$master_car_model_group = new MasterCarModelGroup();
		$trans_statistic_count = new TransStatisticCount();

		if (isset($_REQUEST['make']) && trim($_REQUEST['make'])) {
			$response_array['result'] = 1;

			$model_array = [];
			$car_model_group_array = [];
			$display_number_model_group = 0;
			
			$master_car_memcache_key = "/master_car_model/make/" . $_REQUEST['make'] . '/osc/' . $from_osc;
			
			$master_car_group_model_memcache_key = "/master_car_group_model/make/" . $_REQUEST['make'] . '/osc/' . $from_osc;
			
			$master_car_memcache = Yii::$app->cache->get($master_car_memcache_key);
			$master_car_group_model_memcache = Yii::$app->cache->get($master_car_group_model_memcache_key);
			if ($master_car_memcache !== false && $master_car_group_model_memcache !== false) {
				$model_array = $master_car_memcache;
				$car_model_group_array = $master_car_group_model_memcache;
			} else {

				$tmp_model_array = $master_car_model->getmodelbymake($_REQUEST['make']);
				$model_group_array = $master_car_model_group->getmodelgroup($_REQUEST['make']);
				if (count($tmp_model_array)) {
					foreach ($tmp_model_array as $tmp_model_id_loop => $tmp_model_data_loop) {
						if ($from_osc) {
							$model_array[] = ['id' => $tmp_model_id_loop, 'name' => $tmp_model_data_loop];
						} else {
							$display_number = $trans_statistic_count->displaycount('car_model', $tmp_model_id_loop);
							$is_model_group = false;
							
							if ($display_number !== false) {
								if (count($model_group_array)) {
									foreach ($model_group_array as $model_group_array_loop => $model_group_array_data_loop) {
										// foreach ($model_group_array_data_loop['model_group'] as $model_group_key_loop => $model_group_data_loop) {
										// 	if ($tmp_model_id_loop == $model_group_data_loop) {
										// 		$is_model_group = true;
										// 	}
										// }
									}
									
									if ($is_model_group == false) {
										$model_array[] = ['id' => $tmp_model_id_loop, 'name' => $tmp_model_data_loop . ' ' . $display_number];
									}
								} else {
									$model_array[] = ['id' => $tmp_model_id_loop, 'name' => $tmp_model_data_loop . ' ' . $display_number];
								}
							}
						}
					}
				}
				
				if (count($model_group_array)) {
					$count = 0;
					foreach ($model_group_array as $model_group_array_loop => $model_group_array_data_loop) {
						$count++;
						$group_name = $model_group_array_data_loop['group_name'];
						// $model_group_list = $model_group_array_data_loop['model_group_list'];
						$display_number_model_group = 0;
						// foreach ($model_group_array_data_loop['model_group'] as $model_group_key_loop => $model_group_data_loop) {
						// 	if (count($tmp_model_array)) {
						// 		foreach ($tmp_model_array as $tmp_model_id_loop => $tmp_model_data_loop) {
						// 			$display_number = $trans_statistic_count->displaycount('car_model', $tmp_model_id_loop);
						// 			if ($display_number !== false) {
						// 				if ($tmp_model_id_loop == $model_group_data_loop) {
						// 					$display_number = str_replace(array('(', ')'),"",$display_number);
						// 					$display_number_model_group += $display_number;
						// 					$is_model_group = true;
						// 				}
						// 			}
						// 		}
						// 	}
						// }
						
						if ($is_model_group == true && $display_number_model_group != 0) {
							$car_model_group_array[$count] = ['id' => $model_group_list, 'name' => $group_name . ' ' . '(' . $display_number_model_group . ')'];
						}
					}
				} 

				Yii::$app->cache->set($master_car_memcache_key, $model_array, 240);
				Yii::$app->cache->set($master_car_group_model_memcache_key, $car_model_group_array, 240);
			}
			
			$response_array['message'] = 'Success';
			$response_array['model'] = $model_array;
			$response_array['car_model_group'] = $car_model_group_array;
		}
		
		echo json_encode($response_array);
	}

	public function actionLogin() {
		$response_array = [
			'result'=> 0,
			'message'=> 'Unknown error occurred, please try again.',
		];

		if (isset($_SESSION['user_id']) && trim($_SESSION['user_id'])) {
			$response_array['message'] = 'You have logged in.';
			$response_array['result'] = 1;

		} else if (!isset($_REQUEST['username']) || trim($_REQUEST['username']) == '') {
			$response_array['message'] = 'Invalid username.';

		} else if (!isset($_REQUEST['password']) || trim($_REQUEST['password']) == '') {
			$response_array['message'] = 'Invalid password.';

		} else {
			$username = trim($_REQUEST['username']);
			$password = trim($_REQUEST['password']);

			if ($user_id = Yii::$app->api->login($username, $password, $response_array['message'])) {
				Yii::$app->general->setuserid($user_id, $username);
				
				$response_array['result'] = 1;
				$response_array['message'] = 'Login success';
			}
		}

		echo json_encode($response_array);
	}

	public function actionRegister() {
		$response_array = [
			'result'=> 0,
			'message'=> 'Unknown error occurred, please try again.',
		];

		if (isset($_SESSION['user_id']) && trim($_SESSION['user_id'])) {
			$response_array['message'] = 'You have logged in.';
			$response_array['result'] = 1;


		} else if (!isset($_REQUEST['username']) || trim($_REQUEST['username']) == '') {
			$response_array['message'] = 'Invalid username.';

		} else if (!isset($_REQUEST['password']) || trim($_REQUEST['password']) == '') {
			$response_array['message'] = 'Invalid password.';

		} else if (filter_var($_POST['email'], FILTER_VALIDATE_EMAIL) === false) {
			$response_array['message'] = 'Invalid email.';

		} else if (!isset($_REQUEST['phone']) || trim($_REQUEST['phone']) == '') {
			$response_array['message'] = 'Invalid phone.';

		} else {

			$username = trim($_REQUEST['username']);
			$password = trim($_REQUEST['password']);
			$email = trim($_REQUEST['email']);
			$phone = trim($_REQUEST['phone']);

			$uuid = '';
			$social = '';

			if (isset($_REQUEST['uuid']) && isset($_REQUEST['social']) &&
				trim($_REQUEST['uuid']) && trim($_REQUEST['social'])
			) {
				$uuid = $_REQUEST['uuid'];
				$social = $_REQUEST['social'];
			}

			if ($user_id = Yii::$app->api->register($username, $password, $email, $phone, 'private', $social, $uuid, $response_array['message'])) {
				Yii::$app->general->setuserid($user_id, $username);

				$response_array['result'] = 1;
				$response_array['message'] = 'Register success';
			}
		}

		echo json_encode($response_array);
	}

	public function actionRemovecompare() {
		$response_array = ['result' => 0, 'message' => 'Unknown error occurred, please try again.', 'html' => '', 'count' => ''];

		$trans_order = new TransOrder();		

		if (isset($_REQUEST['urn']) && trim($_REQUEST['urn'])) {
			if (Yii::$app->general->advcompareremove($_REQUEST['urn'])) {
				$response_array['message'] = 'Success';
				$response_array['result'] = 1;
				$compare_total = 0;
				
				$compare_array = Yii::$app->general->advfromcompare();
				if (count($compare_array)) {
					$trans_advert_criteria = ['and', 'urn_no', $compare_array];
					$compare_total = $trans_order->find()->where($trans_advert_criteria)->count();
				}
				
				$response_array['html'] = $this->render('compare', ['urn_no' => $_REQUEST['urn']], true);
			
				if (count($compare_array) > 0) {
					$response_array['count'] = $compare_total;
				} else {
					$response_array['count'] = 0;
				}
			}
		}
		
		echo json_encode($response_array);
	}

	public function actionLoadcompare() {
		$response_array = ['result' => 0, 'message' => 'Unknown error occurred, please try again.', 'html' => '', 'count' => ''];

		$response_array['message'] = 'Success';
		$response_array['result'] = 1;
		$compare_total = 0;

		$trans_order = new TransOrder();
		$super_deals = new SuperDeals();

		$compare_array = Yii::$app->general->advfromcompare();

		if (count($compare_array)) {
			$trans_advert_criteria = ['and', 'urn_no', $compare_array];
			$compare_total= $trans_order->find()->where($trans_advert_criteria)->count();
		}
		
		$response_array['html'] = $this->render('compare', ['trans_order' => $trans_order, 'super_deals' => $super_deals], true);
		$response_array['count'] = $compare_total;
		
		echo json_encode($response_array);
	}
}
?>

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidArgumentException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use app\models\MasterCarMake;
use app\models\MasterCarModelGroup;
use app\models\SuperDeals;
use app\models\TransStatisticCount;
use app\models\TransOrder;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        
        $response_str = Yii::$app->api->wpnews();
        $news_array = json_decode($response_str, true);

        // echo "<pre>";
        // print_r($news_array);
        // exit;

        $master_car_make = new MasterCarMake();
        $master_car_model_group = new MasterCarModelGroup();
        $super_deals = new SuperDeals();
        $trans_statistic_count = new TransStatisticCount();
        $trans_order = new TransOrder();

        $pdata = [];
        
        $featured_cars = $trans_order->featured(1141, 6);
        
        $pdata['superdeals_featured_cnabadv_list'] = ['Featured Cars' => $featured_cars];
        
        return $this->render('index', [
            'news_array' => $news_array,
            'master_car_make' => $master_car_make,
            'master_car_model_group' => $master_car_model_group,
            'super_deals' => $super_deals,
            'trans_statistic_count' => $trans_statistic_count,
            'pdata' => $pdata,
        ]);
    }

     /**
     * Displays login page.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (in_array($_SERVER['REMOTE_ADDR'], ['127.0.0.1', '188.166.181.222', '58.71.205.150', '2001:d08:e2:5e77:d1fe:3726:e0ec:109e', '2001:d08:e2:5e77:912a:4142:613e:3351'])) {
            if (!Yii::$app->general->getuserid()) {
                return $this->render('login');
            } else {
                return $this->redirect(Yii::$app->createAbsoluteUrl('user/index'));
            }
            
        } else {
            $start_date = date('2019-09-01 00:00:00');
            $end_date = date('2019-09-13 23:59:59');
            $current_date = date("Y-m-d 00:00:00");;
            if ($current_date >= $start_date && $current_date <= $end_date) { 
                $this->redirect(Yii::$app->createAbsoluteUrl('site/oscmaintenance'));
            } else {
                if (!Yii::$app->general->getuserid()) {
                    return $this->render('login');
                }
                else {
                    return $this->redirect(Yii::$app->createAbsoluteUrl('user/index'));
                }
            }
        }
    }

    /**
     * Displays terms and condtions.
     *
     * @return mixed
     */
    public function actionTermsAndConditions()
    {
        return $this->render('termsAndConditions');
    }

    /**
     * Displays contact.
     *
     * @return mixed
     */
    public function actionContactUs()
    {
        return $this->render('contactUs');
    }

    /**
     * Displays privacy policy.
     *
     * @return mixed
     */
    public function actionPrivacy()
    {
        return $this->render('privacy');
    }

    /**
     * Displays sitemap.
     *
     * @return mixed
     */
    public function actionSitemap()
    {
        return $this->render('sitemap');
    }

    /**
     * Displays sitemap.
     *
     * @return mixed
     */
    public function actionFaq()
    {
        return $this->render('faq');
    }
}

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?php echo Html::encode($this->title); ?></h1>

    <div class="alert alert-danger">
        <?php echo nl2br(Html::encode($message)); ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/faq_js.php
<script type="text/javascript">
	jQuery("#faq-question").click(function() {
		if(jQuery('#question1').hasClass('in')){
			jQuery('#faq-plus').attr("src", "/images/plus.png");
		} else {
			jQuery('#faq-plus').attr("src", "/images/close.png");
		}
	})

	jQuery("#faq-question-2").click(function() {
		if(jQuery('#question2').hasClass('in')){
			jQuery('#faq-plus-2').attr("src", "/images/plus.png");
		} else {
			jQuery('#faq-plus-2').attr("src", "/images/close.png");
		}
	})

	jQuery("#faq-question-3").click(function() {
		if(jQuery('#question3').hasClass('in')){
			jQuery('#faq-plus-3').attr("src", "/images/plus.png");
		} else {
			jQuery('#faq-plus-3').attr("src", "/images/close.png");
		}
	})

	jQuery("#faq-question-4").click(function() {
		if(jQuery('#question4').hasClass('in')){
			jQuery('#faq-plus-4').attr("src", "/images/plus.png");
		} else {
			jQuery('#faq-plus-4').attr("src", "/images/close.png");
		}
	})

	jQuery("#faq-question-5").click(function() {
		if(jQuery('#question5').hasClass('in')){
			jQuery('#faq-plus-5').attr("src", "/images/plus.png");
		} else {
			jQuery('#faq-plus-5').attr("src", "/images/close.png");
		}
	})

	jQuery("#faq-question-6").click(function() {
		if(jQuery('#question6').hasClass('in')){
			jQuery('#faq-plus-6').attr("src", "/images/plus.png");
		} else {
			jQuery('#faq-plus-6').attr("src", "/images/close.png");
		}
	})

	jQuery("#faq-question-7").click(function() {
		if(jQuery('#question7').hasClass('in')){
			jQuery('#faq-plus-7').attr("src", "/images/plus.png");
		} else {
			jQuery('#faq-plus-7').attr("src", "/images/close.png");
		}
	})

	jQuery("#faq-question-8").click(function() {
		if(jQuery('#question8').hasClass('in')){
			jQuery('#faq-plus-8').attr("src", "/images/plus.png");
		} else {
			jQuery('#faq-plus-8').attr("src", "/images/close.png");
		}
	})

	jQuery("#faq-question-9").click(function() {
		if(jQuery('#question9').hasClass('in')){
			jQuery('#faq-plus-9').attr("src", "/images/plus.png");
		} else {
			jQuery('#faq-plus-9').attr("src", "/images/close.png");
		}
	})

	jQuery("#faq-question-10").click(function() {
		if(jQuery('#question10').hasClass('in')){
			jQuery('#faq-plus-10').attr("src", "/images/plus.png");
		} else {
			jQuery('#faq-plus-10').attr("src", "/images/close.png");
		}
	})

	jQuery("#faq-question-11").click(function() {
		if(jQuery('#question11').hasClass('in')){
			jQuery('#faq-plus-11').attr("src", "/images/plus.png");
		} else {
			jQuery('#faq-plus-11').attr("src", "/images/close.png");
		}
	})

	jQuery("#faq-question-12").click(function() {
		if(jQuery('#question12').hasClass('in')){
			jQuery('#faq-plus-12').attr("src", "/images/plus.png");
		} else {
			jQuery('#faq-plus-12').attr("src", "/images/close.png");
		}
	})

	jQuery("#faq-question-13").click(function() {
		if(jQuery('#question13').hasClass('in')){
			jQuery('#faq-plus-13').attr("src", "/images/plus.png");
		} else {
			jQuery('#faq-plus-13').attr("src", "/images/close.png");
		}
	})

	jQuery("#faq-question-14").click(function() {
		if(jQuery('#question14').hasClass('in')){
			jQuery('#faq-plus-14').attr("src", "/images/plus.png");
		} else {
			jQuery('#faq-plus-14').attr("src", "/images/close.png");
		}
	})
</script>

frontend/views/site/index_js.php
<script>

    jQuery('#icon-box-car').click(function() {
        jQuery("#car-search").removeClass("d-none");
        jQuery("#auto-parts-search").addClass("d-none");
        jQuery("#number-plates-search").addClass("d-none");
        jQuery("#motorcycle-search").addClass("d-none");
        jQuery("#icon-box-car").addClass("active");
        jQuery("#icon-box-auto-parts").removeClass("active");
        jQuery("#icon-box-number-plates").removeClass("active");
        jQuery("#icon-box-motorcycle").removeClass("active");
    });

    jQuery('#icon-box-auto-parts').click(function() {
        jQuery("#auto-parts-search").removeClass("d-none");
        jQuery("#car-search").addClass("d-none");
        jQuery("#number-plates-search").addClass("d-none");
        jQuery("#motorcycle-search").addClass("d-none");
        jQuery("#icon-box-auto-parts").addClass("active");
        jQuery("#icon-box-car").removeClass("active");
        jQuery("#icon-box-number-plates").removeClass("active");
        jQuery("#icon-box-motorcycle").removeClass("active");
        
    });

    jQuery('#icon-box-number-plates').click(function() {
        jQuery("#number-plates-search").removeClass("d-none");
        jQuery("#auto-parts-search").addClass("d-none");
        jQuery("#car-search").addClass("d-none");
        jQuery("#motorcycle-search").addClass("d-none");
        jQuery("#icon-box-number-plates").addClass("active");
        jQuery("#icon-box-car").removeClass("active");
        jQuery("#icon-box-auto-parts").removeClass("active");
        jQuery("#icon-box-motorcycle").removeClass("active");
    });

    jQuery('#icon-box-motorcycle').click(function() {
        jQuery("#motorcycle-search").removeClass("d-none");
        jQuery("#auto-parts-search").addClass("d-none");
        jQuery("#car-search").addClass("d-none");
        jQuery("#number-plates-search").addClass("d-none");
        jQuery("#icon-box-motorcycle").addClass("active");
        jQuery("#icon-box-car").removeClass("active");
        jQuery("#icon-box-auto-parts").removeClass("active");
        jQuery("#icon-box-number-plates").removeClass("active");
    });

    jQuery("#make-home-popup").change(function() {
        loadModel();
    });

    jQuery("#min-price").change(function() {
        for(var i = 0; i < jQuery("#max-price option").length; ++i) {
            if(parseInt(jQuery("#min-price").val()) > parseInt(jQuery("#max-price option")[i].value)) {
                jQuery("#max-price option")[i].setAttribute('disabled', 'disabled');
            } else {
                jQuery("#max-price option")[i].removeAttribute('disabled');
            };
        };
    });

    jQuery("#max-price").change(function() {
        for(var i = 0; i < jQuery("#min-price option").length; ++i) {
            if(parseInt(jQuery("#max-price").val()) < parseInt(jQuery("#min-price option")[i].value)) {
                jQuery("#min-price option")[i].setAttribute('disabled', 'disabled');
            } else {
                jQuery("#min-price option")[i].removeAttribute('disabled');
            };
        };
    });

    jQuery('#icon-box-brands').click(function() {
        jQuery('#list-brands').removeClass("d-none");
        jQuery('#list-type').addClass("d-none");
        jQuery('#icon-box-brands').addClass('active');
         jQuery('#icon-box-type').removeClass('active');
    });

    jQuery('#icon-box-type').click(function() {
        jQuery('#list-type').removeClass("d-none");
        jQuery('#list-brands').addClass("d-none");
        jQuery('#icon-box-brands').removeClass('active');
         jQuery('#icon-box-type').addClass('active');
    });

    jQuery('#show-more-cars').click(function() {
        if(jQuery('#all-shown-cars').hasClass('d-none')) {
            jQuery('#all-shown-cars').removeClass('d-none');
        } else {
            jQuery('#all-shown-cars').addClass('d-none');
        }
    });

    function loadModel(){
        var make = jQuery("#make-home-popup").val();
        if (make != '') {
            jQuery.ajax({
                type: 'POST',
                dataType: 'json',
                url: '<?php echo Yii::$app->urlManager->createAbsoluteUrl('ajax/model'); ?>',
                data: {
                    'make': make
                },
                success: function(data){
                    if (data.result == 1) {
                        var display_html = '';
                        display_html += '<option value="">All Models</option>';
                        if (data.result == '1') {
                            jQuery.each(data.model, function(i, item) {
                                display_html += '<option value="' + item.id + '">' + item.name + '</option>';
                            });
                        }
                        jQuery("#model-home-popup").html(display_html).attr('disabled', false);
                    } else {
                        alert(data.message);
                    }
                }     
            });
        } else {
            jQuery("#model-home-popup").html('<option value="">All Models</option>').attr('disabled', true);
        }

        jQuery("#model-home-popup").html('<option value="">All Models</option>').attr('disabled', true);
    }

    window.addEventListener("load", function(event) {
        lazyload();
    }); 
</script>

frontend/views/site/login_js.php
<script>
jQuery(document).ready(function() {
    jQuery( "#frm-login" ).submit(function( event ) {
      event.preventDefault();

      jQuery.ajax({
          type: 'post',
          url: '<?php echo Yii::$app->urlManager->createAbsoluteUrl('ajax/login')?>',
          dataType: 'json',
          data: jQuery('#frm-login').serialize(),
          timeout: 120000,
          beforeSend : function(){
            //
          },
          success: function(data) {
            if (data.result == '1') {
              window.location.href = '<?php echo Yii::$app->urlManager->createAbsoluteUrl('user') ?>';
            } else {
              mtalert(data.message);
            }
          }
      });
  });

  jQuery( "#frm-register" ).submit(function( event ) {
        event.preventDefault();

        if (jQuery("#register-agree:checked").length) {
          jQuery.ajax({
              type: 'post',
              url: '<?php echo Yii::$app->urlManager->createAbsoluteUrl('ajax/register')?>',
              dataType: 'json',
              data: jQuery('#frm-register').serialize(),
              timeout: 120000,
              beforeSend : function(){
                //
              },
              success: function(data) {
                mtalert(data.message);
                jQuery("#alert-primary .btn-primary").click(function() {
                  if (data.result == '1') {
                    window.location.href = '<?php echo Yii::$app->urlManager->createAbsoluteUrl('user') ?>';
                  }
                });
              }
          });
        } else {
          mtalert("Please read and agree our terms and conditions");
        }
    });
});
</script>